# linkspector config file is described at https://github.com/UmbrellaDocs/linkspector/blob/main/README.md#configuration
dirs:
  - .
excludedFiles:
  - ./CHANGELOG.md
useGitIgnore: true
followRedirects: true
