name: File Checks

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  markdown-lint-check:
    name: Markdown Lint Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # equivalent cli: markdownlint-cli2  "**/*.md" "!**/CHANGELOG.md"  --config .markdownlint-cli2.yaml
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
        with:
          config: .markdownlint-cli2.yaml
          fix: false
          globs: |
            **/*.md

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write # required for posting PR review comments
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@6c637d70424624231467a4ca918be54fa3b792d0 # v1.5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_on_error: true

  ruby-check:
    name: RuboCop Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: "3.3.11"
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop
