name: File Checks

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  markdown-lint-check:
    name: Markdown Lint Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      # equivalent cli: markdownlint-cli2  "**/*.md" "!**/CHANGELOG.md"  --config .markdownlint-cli2.yaml
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b # v23.1.0
        with:
          config: .markdownlint-cli2.yaml
          fix: false
          globs: |
            **/*.md

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write # required for posting PR review comments
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@6c637d70424624231467a4ca918be54fa3b792d0 # v1.5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_on_error: true

  ruby-check:
    name: RuboCop Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: "3.3.11"
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop
