name: File Checks

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  markdown-lint-check:
    name: Markdown Lint Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # equivalent cli: markdownlint-cli2  "**/*.md" "!**/CHANGELOG.md"  --config .markdownlint-cli2.yaml
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
        with:
          config: .markdownlint-cli2.yaml
          fix: false
          globs: |
            **/*.md

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write # required for posting PR review comments
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@6c637d70424624231467a4ca918be54fa3b792d0 # v1.5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_on_error: true

  ruby-check:
    name: RuboCop Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: "3.3.11"
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop
