name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-instrumentation' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: "4.0.5"
          bundler-cache: true

      - uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c # v2.0.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          team: OpenTelemetry
