name: "[release hook] Process release"

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  release-process-request:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-instrumentation' }}
    permissions:
      contents: write # required for creating releases
      pull-requests: write # required for updating release PRs
      issues: write # required to create issues for failed releases
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: "4.0.5"

      - name: Install Toys
        run: gem install --no-document toys:0.22.0 toys-release:0.9.1

      - name: Create otelbot app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.OTELBOT_RUBY_INSTRUMENTATION_CLIENT_ID }}
          private-key: ${{ secrets.OTELBOT_RUBY_INSTRUMENTATION_PRIVATE_KEY }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write

      - name: Process release request
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          EVENT_PATH: ${{ github.event_path }}
        run: |
          toys release _onclosed --verbose \
            "--event-path=$EVENT_PATH" \
            < /dev/null
